[build]
publish = "dist"

command = """
    rustup update nightly && \
    rustup default nightly && \
    rustup target add wasm32-unknown-unknown && \
    wget -qO- https://github.com/thedodd/trunk/releases/latest/download/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf- && \
    ./build.sh --ci --wasm --wasm-rayon
  """


[[headers]]
for = "/*"
[headers.values]
Cross-Origin-Opener-Policy = "same-origin"
Cross-Origin-Embedder-Policy = "require-corp"
